GET http://localhost:4000/orders/getAll

### get order by customer id
GET http://localhost:4000/orders/get/12

### Creating Restaurant
POST http://localhost:4000/orders/create
Content-Type: application/json

{
  "total_amount": 150,
  "total_points": 200,
  "pickup_time": "2023-09-16T09:50:00.000Z",
  "customer_id": 5
}

###
PUT http://localhost:4000/orders/update/4
Content-Type: application/json

{
  "pickup_time": "2023-10-16T09:50:00.000Z"
}

###
DELETE http://localhost:4000/orders/delete/4